spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/lsh/h2_db_collection/utilJPA/utilJPA
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none #create
    properties:
      hibernate:
#        show_sql: true => sys.out 으로 로그를 남김
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#      multiline: true